use std::sync::Arc;
use tracing::info;

use super::llm_client::{LlmClient, LlmMessage};
use super::response_parser;
use crate::action::types::{Action, ActionSource};
use crate::error::LunaError;
use crate::memory::MemorySystem;

pub struct ConductorAgent {
    pub id: String,
    llm_client: LlmClient,
    conversation_history: Vec<LlmMessage>,
}

impl ConductorAgent {
    pub fn new(llm_client: LlmClient) -> Self {
        Self {
            id: "conductor".to_string(),
            llm_client,
            conversation_history: Vec::new(),
        }
    }

    /// Handle user input. Returns a list of actions to execute.
    /// `action_space` is a pre-generated action space string from the registry
    /// (generated by the caller to avoid holding the registry lock here).
    pub async fn handle_user_input(
        &mut self,
        text: String,
        action_space: Option<String>,
        memory: Option<&Arc<MemorySystem>>,
        open_windows: Vec<String>,
        session_id: &str,
    ) -> Result<Vec<Action>, LunaError> {
        // Build system prompt
        let recent_memory = if let Some(mem) = memory {
            mem.episodic.recent_summary(session_id, 10)
        } else {
            "Memory not available.".to_string()
        };

        let system_prompt = if let Some(space) = action_space {
            let window_list = if open_windows.is_empty() {
                "None".to_string()
            } else {
                open_windows.join(", ")
            };
            format!(
                "You are the Conductor for Luna OS — an LLM-native operating system.\n\
                You receive user input and respond with structured JSON actions.\n\n\
                ## Current Context\n\
                - Open windows: {window_list}\n\
                - Active workspace: workspace_default\n\
                - Recent memory:\n{recent_memory}\n\n\
                {space}\n\n\
                ## Response Format\n\
                Respond ONLY with a JSON array of actions. No markdown outside the JSON.\n\
                Always include agent.response if you want to communicate text to the user.\n\
                Example: [{{\"action_type\": \"agent.response\", \"payload\": {{\"text\": \"Hello!\"}}}}]\n"
            )
        } else {
            FALLBACK_SYSTEM_PROMPT.to_string()
        };

        // Add user message to history
        self.conversation_history.push(LlmMessage {
            role: "user".to_string(),
            content: text.clone(),
        });

        // Keep history bounded (last 20 messages)
        if self.conversation_history.len() > 20 {
            let drain = self.conversation_history.len() - 20;
            self.conversation_history.drain(..drain);
        }

        info!(
            history_len = self.conversation_history.len(),
            "Conductor processing user input"
        );

        // Send to LLM
        let response = self
            .llm_client
            .send(&system_prompt, &self.conversation_history, 4096)
            .await?;

        // Track token usage
        if let Some(mem) = memory {
            let _ = mem.agent_state.record_tokens(
                &self.id,
                response.input_tokens,
                response.output_tokens,
            );
        }

        // Add assistant response to history
        self.conversation_history.push(LlmMessage {
            role: "assistant".to_string(),
            content: response.content.clone(),
        });

        // Parse response into actions, with rephrase retry on failure.
        // Clone what we need so the closure doesn't borrow self.
        let retry_client = self.llm_client.clone();
        let retry_prompt = system_prompt.clone();
        let retry_user_text = text.clone();
        let retry_content = response.content.clone();

        let actions = response_parser::parse_response_with_retry(
            &response.content,
            &self.id,
            move || {
                let client = retry_client;
                let prompt = retry_prompt;
                let retry_msgs = vec![
                    LlmMessage { role: "user".to_string(), content: retry_user_text },
                    LlmMessage { role: "assistant".to_string(), content: retry_content },
                    LlmMessage {
                        role: "user".to_string(),
                        content: "Your previous response could not be parsed. Please respond with ONLY a valid JSON array of actions.".to_string(),
                    },
                ];
                async move {
                    client.send(&prompt, &retry_msgs, 2048).await
                        .map(|r| r.content)
                        .unwrap_or_default()
                }
            }
        ).await;

        info!(
            action_count = actions.len(),
            input_tokens = response.input_tokens,
            output_tokens = response.output_tokens,
            "Conductor produced actions"
        );

        // Record episodic event
        if let Some(mem) = memory {
            let _ = mem.episodic.record(
                session_id,
                &self.id,
                "user.input_handled",
                &serde_json::json!({"text": &text}),
                &serde_json::json!({"action_count": actions.len()}),
                &["conductor".to_string(), "user_input".to_string()],
            );
        }

        Ok(actions)
    }

    /// Check if the Conductor should delegate to the orchestrator.
    pub fn should_delegate(&self, text: &str) -> bool {
        let multi_step = ["and then", "after that", "first", "step by step", "multiple",
            "create and", "build and", "research and"];
        let lower = text.to_lowercase();
        multi_step.iter().any(|indicator| lower.contains(indicator))
    }

    /// Create a delegation action for the orchestrator.
    pub fn make_delegate_action(task: &str, workspace_id: &str) -> Action {
        Action::new(
            "agent.delegate".to_string(),
            serde_json::json!({
                "task": task,
                "workspace_id": workspace_id
            }),
            ActionSource::Agent("conductor".to_string()),
        )
    }
}

const FALLBACK_SYSTEM_PROMPT: &str = r#"You are the Conductor for Luna OS — an LLM-native operating system.
Respond ONLY with a JSON array of actions.

Available actions:
- "agent.response" — {"text": "your response"}
- "window.create" — {"title": "Title", "content_type": "response"}
- "agent.delegate" — {"task": "task description", "workspace_id": "workspace_default"}

Example: [{"action_type": "agent.response", "payload": {"text": "Hello!"}}]
"#;
